name: debatable
channels:
  - conda-forge
dependencies:
  - python=3.9
  - tqdm
  - textblob
  - bs4
  - pyyaml
  - numpy
  - newspaper3k
  - wordfreq
  - sentence-transformers
  - jupyter
  - vulture
  - yapf
  - tk
  - scikit-learn