# General Settings:
debug: False # Show debug messages?
multiProcessing: "L2" # L0 for no multiprocessing. L1 for multiprocessing runner process. L2 for multiprocessing page retrieval
showLoadingBars: False # Show loading bars? This is only useful when there is an input file with multiple links (otherwise there is only 1 link to check anyway)

# Article Retrieval Settings:
keyTermsMethod: "title" # "title" or "common". Method to be used for key term extraction from original article
numOfSourcesToLoad: 10 # Number of sources to attempt to load from each search engine
webpageLoadingTimeout: 15 # Seconds after which there is a timeout error when trying to load a webpage

# Headline comparison Settings:
headlineSimFilter: True # Filter articles based on headline similarity to make sure they are on the same topic?
titleSimilarityThreshold: 0.4 # Similarity threshold for headline similarity filter
model: "continuedLearningall-mpnet-base-v1-2023-01-04_15-58-07" # Name of the folder where the model resides

# Content comparison Settings:
useOfTFIDF: Yes # Use TF-IDF to compare the content of the articles? Alternative is a simple word count method using the Fitts distribution

# Output Settings
exportOutput: True # Export the output to a file? If the GUI is used, the results are not saved in a file
outputFile: "output" # Name of output file
